Build and publish v0.28.0 packages manually
GitHub didn't trigger CircleCI and AppVeyor with the tag build, so this
is a hack to do this manually.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,95 +1,95 @@
 version: 2
 jobs:
-  deps:
-    docker:
-      - image: circleci/golang:1.14
-    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
-    steps:
-      - checkout
-      - run:
-          name: Check dependencies
-          command: |
-            go version
-            test -z "$(go mod vendor && git status --porcelain)"
-            go mod verify
+  # deps:
+  #   docker:
+  #     - image: circleci/golang:1.14
+  #   working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Check dependencies
+  #         command: |
+  #           go version
+  #           test -z "$(go mod vendor && git status --porcelain)"
+  #           go mod verify
 
-  lint:
-    docker:
-      - image: circleci/golang:1.14
-    environment:
-      GOLANGCI_VERSION: v1.30.0
-      GO111MODULE: 'on'
-    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
-    steps:
-      # Workaround for custom env vars not available in cache keys
-      # https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/8
-      - run: echo $GOLANGCI_VERSION > /tmp/.golangci.version
-      - restore_cache:
-          name: Restore golangci-lint cache
-          key: golangci-lint-{{ arch }}-{{ checksum "/tmp/.golangci.version" }}-{{ .Environment.CACHE_VERSION }}
-          paths:
-            - /go/bin/golangci-lint
-      - run:
-          name: Install golangci-lint
-          command: |
-            command -v golangci-lint && exit
-            go get github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_VERSION
-      - save_cache:
-          name: Save golangci-lint cache
-          key: golangci-lint-{{ arch }}-{{ checksum "/tmp/.golangci.version" }}-{{ .Environment.CACHE_VERSION }}
-          paths:
-            - /go/bin/golangci-lint
-      - checkout
-      - run:
-          name: Run golangci-lint
-          command: |
-            BASEREV=$(git merge-base HEAD origin/master)
-            echo "Base revision: $BASEREV"
-            golangci-lint run --out-format=tab --new-from-rev "$BASEREV" ./...
+  # lint:
+  #   docker:
+  #     - image: circleci/golang:1.14
+  #   environment:
+  #     GOLANGCI_VERSION: v1.30.0
+  #     GO111MODULE: 'on'
+  #   working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
+  #   steps:
+  #     # Workaround for custom env vars not available in cache keys
+  #     # https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/8
+  #     - run: echo $GOLANGCI_VERSION > /tmp/.golangci.version
+  #     - restore_cache:
+  #         name: Restore golangci-lint cache
+  #         key: golangci-lint-{{ arch }}-{{ checksum "/tmp/.golangci.version" }}-{{ .Environment.CACHE_VERSION }}
+  #         paths:
+  #           - /go/bin/golangci-lint
+  #     - run:
+  #         name: Install golangci-lint
+  #         command: |
+  #           command -v golangci-lint && exit
+  #           go get github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_VERSION
+  #     - save_cache:
+  #         name: Save golangci-lint cache
+  #         key: golangci-lint-{{ arch }}-{{ checksum "/tmp/.golangci.version" }}-{{ .Environment.CACHE_VERSION }}
+  #         paths:
+  #           - /go/bin/golangci-lint
+  #     - checkout
+  #     - run:
+  #         name: Run golangci-lint
+  #         command: |
+  #           BASEREV=$(git merge-base HEAD origin/master)
+  #           echo "Base revision: $BASEREV"
+  #           golangci-lint run --out-format=tab --new-from-rev "$BASEREV" ./...
 
 
-  test:
-    docker:
-      - image: circleci/golang:1.14
-    environment:
-      GOPATH: /home/circleci/.go_workspace
-    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
-    steps:
-      - checkout
-      - run:
-          name: Run tests and code coverage
-          command: |
-            go version
-            export GOMAXPROCS=2
-            export PATH=$GOPATH/bin:$PATH
-            echo "mode: set" > coverage.txt
-            for pkg in $(go list ./... | grep -v vendor); do
-                list=$(go list -test -f  '{{ join .Deps  "\n"}}' $pkg | grep github.com/loadimpact/k6 | grep -v vendor || true)
-                if [ -n "$list" ]; then
-                    list=$(echo "$list" | cut -f1 -d ' ' | sort -u | paste -sd,)
-                fi
+  # test:
+  #   docker:
+  #     - image: circleci/golang:1.14
+  #   environment:
+  #     GOPATH: /home/circleci/.go_workspace
+  #   working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Run tests and code coverage
+  #         command: |
+  #           go version
+  #           export GOMAXPROCS=2
+  #           export PATH=$GOPATH/bin:$PATH
+  #           echo "mode: set" > coverage.txt
+  #           for pkg in $(go list ./... | grep -v vendor); do
+  #               list=$(go list -test -f  '{{ join .Deps  "\n"}}' $pkg | grep github.com/loadimpact/k6 | grep -v vendor || true)
+  #               if [ -n "$list" ]; then
+  #                   list=$(echo "$list" | cut -f1 -d ' ' | sort -u | paste -sd,)
+  #               fi
 
-                go test -race -timeout 800s  --coverpkg="$list" -coverprofile=$(echo $pkg | tr / -).coverage $pkg
-            done
-            grep -h -v "^mode:" *.coverage >> coverage.txt
-            rm -f *.coverage
-            bash <(curl --fail -s https://codecov.io/bash)
+  #               go test -race -timeout 800s  --coverpkg="$list" -coverprofile=$(echo $pkg | tr / -).coverage $pkg
+  #           done
+  #           grep -h -v "^mode:" *.coverage >> coverage.txt
+  #           rm -f *.coverage
+  #           bash <(curl --fail -s https://codecov.io/bash)
 
   #TODO: when we officially move to Go 1.15, re-enable test-prev-golang with 1.14
 
-  test-next-golang:
-    docker:
-      - image: circleci/golang:1.15
-    working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
-    steps:
-      - checkout
-      - run:
-          name: Run tests with next Go version
-          command: |
-            go version
-            export GOMAXPROCS=2
-            export PATH=$GOPATH/bin:$PATH
-            go test -p 2 -race -timeout 800s ./...
+  # test-next-golang:
+  #   docker:
+  #     - image: circleci/golang:1.15
+  #   working_directory: /home/circleci/.go_workspace/src/github.com/loadimpact/k6
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Run tests with next Go version
+  #         command: |
+  #           go version
+  #           export GOMAXPROCS=2
+  #           export PATH=$GOPATH/bin:$PATH
+  #           go test -p 2 -race -timeout 800s ./...
 
   build-docker-images:
     docker:
@@ -106,6 +106,7 @@ jobs:
       - run:
           name: Build application Docker image
           command: |
+            git checkout v0.28.0
             docker build -t loadimpact/k6 .
       - run:
           name: Run tests on generated Docker image
@@ -122,14 +123,9 @@ jobs:
       - deploy:
           name: Push application Docker image
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              docker tag loadimpact/k6 loadimpact/k6:master
-              docker push loadimpact/k6:master
-            elif [[ "${CIRCLE_TAG}" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
-              docker tag loadimpact/k6 loadimpact/k6:${CIRCLE_TAG:1}
+              docker tag loadimpact/k6 loadimpact/k6:0.28.0
               docker push loadimpact/k6:latest
-              docker push loadimpact/k6:${CIRCLE_TAG:1}
-            fi
+              docker push loadimpact/k6:0.28.0
 
   build-linux-packages:
     docker:
@@ -143,7 +139,10 @@ jobs:
           name: Build linux packages
           command: |
             export PATH=$GOPATH/bin:$PATH
+            set -x
 
+            tmpdir=$(mktemp -d)
+            cd "$tmpdir"
             go get github.com/Masterminds/glide
             go get -d github.com/mh-cbon/go-bin-deb \
               && cd $GOPATH/src/github.com/mh-cbon/go-bin-deb \
@@ -159,17 +158,19 @@ jobs:
             sudo apt-get install -y fakeroot rpm
 
             cd $GOPATH/src/github.com/loadimpact/k6
+            git checkout v0.28.0
 
             echo "Building k6..."
             CGO_ENABLED=0 GOARCH=amd64 go build -a -trimpath -ldflags "-s -w -X github.com/loadimpact/k6/lib/consts.VersionDetails=$(date -u +"%FT%T%z")/$(git describe --always --long --dirty)" -o /tmp/k6
             echo "Done!"
 
-            VERSION=${CIRCLE_TAG:1} ./packaging/gen-packages.sh
+            VERSION=0.28.0 ./packaging/gen-packages.sh
+            ls -al dist/
 
       - deploy:
           name: Publish packages in Bintray
           command: |
-            export VERSION=${CIRCLE_TAG:1}
+            export VERSION=0.28.0
             # Publishing deb
             curl --fail -H "X-GPG-PASSPHRASE: $GPG_PASSPHRASE" -T dist/k6-v$VERSION-amd64.deb "https://$BINTRAY_USER:$BINTRAY_KEY@api.bintray.com/content/loadimpact/deb/k6/$VERSION/k6-v$VERSION-amd64.deb;deb_distribution=stable;deb_component=main;deb_architecture=amd64;publish=1;override=1"
             # Publishing rpm
@@ -180,34 +181,34 @@ workflows:
   version: 2
   test_and_build:
     jobs:
-      - deps:
-          filters:
-            tags:
-              only: /.*/
-      - lint
-      - test:
-          filters:
-            tags:
-              only: /.*/
-      - test-next-golang:
-          filters:
-            tags:
-              only: /.*/
-      - build-docker-images:
-          requires:
-            - deps
-            - lint
-            - test
-          filters:
-            tags:
-              only: /.*/
-      - build-linux-packages:
-          requires:
-            - deps
-            - lint
-            - test
-          filters:
-            branches:
-              ignore: /.*/
-            tags:
-              only: /^v.*/
+      # - deps:
+      #     filters:
+      #       tags:
+      #         only: /.*/
+      # - lint
+      # - test:
+      #     filters:
+      #       tags:
+      #         only: /.*/
+      # - test-next-golang:
+      #     filters:
+      #       tags:
+      #         only: /.*/
+      - build-docker-images
+          # requires:
+          #   - deps
+          #   - lint
+          #   - test
+          # filters:
+          #   tags:
+          #     only: /.*/
+      - build-linux-packages
+          # requires:
+          #   - deps
+          #   - lint
+          #   - test
+          # filters:
+          #   branches:
+          #     ignore: /.*/
+          #   tags:
+          #     only: /^v.*/
