Refactor workflow
- Refactor workflow so that the Windows binary can be signed before it is added to the Windows installer.
- Avoid string interpolation in shell commands.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,19 +35,21 @@ jobs:
     outputs:
       k6_version: ${{ steps.get_k6_version.outputs.k6_version }}
       go_version: ${{ steps.get_go_version.outputs.go_version }}
+      sign_windows_artifacts: ${{ steps.determine_windows_signing.outputs.sign_windows_artifacts }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v5
         with:
           fetch-depth: 0
           persist-credentials: false
+
       - name: Get the k6 version
         id: get_k6_version
         env:
           INPUT_K6_VERSION: ${{ github.event.inputs.k6_version  }}
         run: |
           set -x # Show exactly what commands are executed
-          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${INPUT_K6_VERSION}" != "" ]]; then
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]] && [[ "${INPUT_K6_VERSION}" != "" ]]; then
             VERSION="${INPUT_K6_VERSION}"
             echo "Building custom dev build with version '${VERSION}' from manual workflow_dispatch..."
           elif [[ "${GITHUB_REF}" =~ ^refs/tags/v.+$ ]]; then
@@ -59,13 +61,14 @@ jobs:
           fi
           echo "VERSION=${VERSION}"
           echo "k6_version=${VERSION}" >> $GITHUB_OUTPUT
+
       - name: Get the used Go version
         id: get_go_version
         env:
           INPUT_GO_VERSION: ${{ github.event.inputs.go_version  }}
         run: |
           set -x # Show exactly what commands are executed
-          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${INPUT_GO_VERSION}" != "" ]]; then
+          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]] && [[ "${INPUT_GO_VERSION}" != "" ]]; then
             GO_VERSION="${INPUT_GO_VERSION}"
             echo "Using custom Go version '${GO_VERSION}' from manual workflow_dispatch..."
           else
@@ -74,6 +77,28 @@ jobs:
           fi
           echo "GO_VERSION=${GO_VERSION}"
           echo "go_version=${GO_VERSION}" >> $GITHUB_OUTPUT
+
+      # GH secrets are unavailable when building from project forks, so this
+      # will fail for external PRs, even if we wanted to do it. And we don't.
+      # We are only going to sign packages that are built from the default branch
+      # or a version tag, or manually triggered dev builds, so we have enough
+      # assurance that package signing works, but don't sign every PR build.
+      - name: Determine whether to sign the Windows artifacts
+        id: determine_windows_signing
+        env:
+          SIGN_FILES: 'true'
+          # TODO Enable after testing
+          #SIGN_FILES: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
+        run: |
+          set -x # Show exactly what commands are executed
+          if [[ "${SIGN_FILES}" == "true" ]]; then
+            echo "Windows artifacts will be signed"
+            sign_windows_artifacts="true"
+          else
+            echo "Windows artifacts will not be signed"
+            sign_windows_artifacts="true"
+          fi
+          echo "sign_windows_artifacts=${sign_windows_artifacts}" >> ${GITHUB_OUTPUT}
 
   build:
     runs-on: ubuntu-latest
@@ -228,6 +253,112 @@ jobs:
             -t $DOCKER_IMAGE_ID:latest-with-browser \
             -t ghcr.io/$GHCR_IMAGE_ID:latest-with-browser .
 
+  sign-windows-binary:
+    permissions:
+      actions: read
+      contents: read
+      id-token: write # Required for Vault
+
+    env:
+      VERSION: ${{ needs.configure.outputs.k6_version }}
+
+    environment:
+      name: azure-trusted-signing
+
+    runs-on: windows-latest
+    defaults:
+      run:
+        shell: pwsh
+    needs: [configure, build]
+    steps:
+      - name: Download binaries
+        uses: actions/download-artifact@v4
+        with:
+          name: binaries
+          path: dist
+
+      - name: Unzip Windows binary
+        run: |
+          Expand-Archive -Path ".\dist\k6-${env:VERSION}-windows-amd64.zip" -DestinationPath .\packaging\
+
+      - name: Setup .NET SDK
+        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
+        with:
+          # renovate: datasource=dotnet-version depName=dotnet-sdk
+          dotnet-version: '8.0.413'
+
+      - name: Install Sign CLI tool
+        env:
+          # renovate: datasource=nuget depName=sign
+          DOTNET_SIGN_VERSION: '0.9.1-beta.25379.1'
+        run: dotnet tool install --tool-path . sign --version ${env:DOTNET_SIGN_VERSION}
+
+      - name: Get secrets for Azure Trusted Signing
+        uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets/v1.3.0
+        id: get-signing-secrets
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
+        with:
+          export_env: false
+          repo_secrets: |
+            client-id=azure-trusted-signing:client-id
+            subscription-id=azure-trusted-signing:subscription-id
+            tenant-id=azure-trusted-signing:tenant-id
+
+      - name: Azure log in
+        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
+        with:
+          client-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).client-id }}
+          subscription-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).subscription-id }}
+          tenant-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).tenant-id }}
+
+      - name: Sign Windows binary
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
+        env:
+          APPLICATION_DESCRIPTION: 'Grafana k6'
+          PUBLISHER_NAME: 'Grafana Labs'
+          TRUSTED_SIGNING_ACCOUNT: 'grafana-premium-eastus'
+          TRUSTED_SIGNING_ENDPOINT: 'https://eus.codesigning.azure.net/'
+          TRUSTED_SIGNING_PROFILE: 'grafana-production'
+          VERBOSITY: ${{ runner.debug == '1' && 'Debug' || 'Error' }}
+        run: |
+          ./sign code trusted-signing `
+            **/*.exe `
+            --base-directory "${env:GITHUB_WORKSPACE}/packaging" `
+            --application-name ${env:APPLICATION_DESCRIPTION} `
+            --publisher-name ${env:PUBLISHER_NAME} `
+            --description ${env:APPLICATION_DESCRIPTION} `
+            --description-url "${env:GITHUB_SERVER_URL}/${env:GITHUB_REPOSITORY}" `
+            --trusted-signing-account ${env:TRUSTED_SIGNING_ACCOUNT} `
+            --trusted-signing-certificate-profile ${env:TRUSTED_SIGNING_PROFILE} `
+            --trusted-signing-endpoint ${env:TRUSTED_SIGNING_ENDPOINT} `
+            --verbosity "${env:VERBOSITY}"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Output "::error::Failed to sign Windows binary"
+            exit 1
+          }
+
+      - name: Zip signed Windows binary
+        run: |
+          Compress-Archive -Path ".\packaging\*" -DestinationPath ".\dist\k6-${env:VERSION}-windows-amd64.zip" -Force
+
+      - name: Upload signed artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: binaries-signed
+          path: dist/
+          retention-days: 7
+          if-no-files-found: error
+
+      - name: Upload signed Windows binary
+        uses: actions/upload-artifact@v4
+        with:
+          name: signed-windows-binary
+          path: |
+            packaging/k6.exe
+          retention-days: 7
+          if-no-files-found: error
+
   package-windows:
     permissions:
       contents: read
@@ -237,7 +368,7 @@ jobs:
     defaults:
       run:
         shell: pwsh
-    needs: [configure, build]
+    needs: [configure, build, sign-windows-binary]
     env:
       VERSION: ${{ needs.configure.outputs.k6_version }}
     steps:
@@ -245,25 +376,23 @@ jobs:
         uses: actions/checkout@v5
         with:
           persist-credentials: false
+
       - name: Install pandoc
         uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333 # v3.0.0
         with:
           args: install -y pandoc
+
       - name: Install wix tools
         run: |
           curl -Lso wix311-binaries.zip https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
           Expand-Archive -Path .\wix311-binaries.zip -DestinationPath .\wix311\
           echo "$pwd\wix311" | Out-File -FilePath $env:GITHUB_PATH -Append
-      - name: Download binaries
+
+      - name: Download signed Windows binary
         uses: actions/download-artifact@v4
         with:
-          name: binaries
-          path: dist
-      - name: Unzip Windows binary
-        run: |
-          Expand-Archive -Path ".\dist\k6-$env:VERSION-windows-amd64.zip" -DestinationPath .\packaging\
-          move .\packaging\k6-$env:VERSION-windows-amd64\k6.exe .\packaging\
-          rmdir .\packaging\k6-$env:VERSION-windows-amd64\
+          name: signed-windows-binary
+          path: packaging
 
       - name: Create the MSI package
         run: |
@@ -277,7 +406,7 @@ jobs:
         # To keep it consistent with the other artifacts
         run: move "packaging\k6.msi" "packaging\k6-$env:VERSION-windows-amd64.msi"
 
-      - name: Upload artifacts
+      - name: Upload unsigned Windows installer
         uses: actions/upload-artifact@v4
         with:
           name: binaries-windows-unsigned
@@ -286,7 +415,7 @@ jobs:
           retention-days: 7
           if-no-files-found: error
 
-  sign-windows:
+  sign-windows-installer:
     permissions:
       actions: read
       contents: read
@@ -299,16 +428,7 @@ jobs:
     defaults:
       run:
         shell: pwsh
-    needs: [package-windows]
-    env:
-      # GH secrets are unavailable when building from project forks, so this
-      # will fail for external PRs, even if we wanted to do it. And we don't.
-      # We are only going to sign packages that are built from the default branch
-      # or a version tag, or manually triggered dev builds, so we have enough
-      # assurance that package signing works, but don't sign every PR build.
-      SIGN_FILES: 'true'
-      # TODO Enable after testing
-      #SIGN_FILES: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
+    needs: [configure, package-windows]
     steps:
       - name: Download unsigned Windows artifacts
         uses: actions/download-artifact@v4
@@ -318,13 +438,13 @@ jobs:
 
       - name: Setup .NET SDK
         uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
-        if: env.SIGN_FILES == 'true'
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
         with:
           # renovate: datasource=dotnet-version depName=dotnet-sdk
           dotnet-version: '8.0.413'
 
       - name: Install Sign CLI tool
-        if: env.SIGN_FILES == 'true'
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
         env:
           # renovate: datasource=nuget depName=sign
           DOTNET_SIGN_VERSION: '0.9.1-beta.25379.1'
@@ -333,7 +453,7 @@ jobs:
       - name: Get secrets for Azure Trusted Signing
         uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets/v1.3.0
         id: get-signing-secrets
-        if: env.SIGN_FILES == 'true'
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
         with:
           export_env: false
           repo_secrets: |
@@ -342,15 +462,15 @@ jobs:
             tenant-id=azure-trusted-signing:tenant-id
 
       - name: Azure log in
-        if: env.SIGN_FILES == 'true'
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
         uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
         with:
           client-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).client-id }}
           subscription-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).subscription-id }}
           tenant-id: ${{ fromJSON(steps.get-signing-secrets.outputs.secrets).tenant-id }}
 
-      - name: Sign Windows binary and .msi package
-        if: env.SIGN_FILES == 'true'
+      - name: Sign Windows installer
+        if: needs.configure.outputs.sign_windows_artifacts == 'true'
         env:
           APPLICATION_DESCRIPTION: 'Grafana k6'
           PUBLISHER_NAME: 'Grafana Labs'
@@ -360,7 +480,7 @@ jobs:
           VERBOSITY: ${{ runner.debug == '1' && 'Debug' || 'Error' }}
         run: |
           ./sign code trusted-signing `
-            **/* `
+            **/*.msi `
             --base-directory "${env:GITHUB_WORKSPACE}/packaging" `
             --application-name ${env:APPLICATION_DESCRIPTION} `
             --publisher-name ${env:PUBLISHER_NAME} `
@@ -371,14 +491,14 @@ jobs:
             --trusted-signing-endpoint ${env:TRUSTED_SIGNING_ENDPOINT} `
             --verbosity "${env:VERBOSITY}"
           if ($LASTEXITCODE -ne 0) {
-            Write-Output "::error::Failed to sign Windows artifacts"
+            Write-Output "::error::Failed to sign Windows installer"
             exit 1
           }
 
-      - name: Upload artifacts
+      - name: Upload signed Windows installer
         uses: actions/upload-artifact@v4
         with:
-          name: binaries-windows
+          name: binaries-windows-signed
           path: |
             packaging/k6-*.msi
           retention-days: 7
@@ -387,7 +507,7 @@ jobs:
   # TODO Temporarily disabled to avoid accidental publish while testing
   # publish-github:
   #   runs-on: ubuntu-latest
-  #   needs: [configure, build, package-windows, sign-windows]
+  #   needs: [configure, build, sign-windows-installer]
   #   if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' }}
   #   env:
   #     VERSION: ${{ needs.configure.outputs.k6_version }}
@@ -399,15 +519,15 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         persist-credentials: false
-  #     - name: Download binaries
+  #     - name: Download signed binaries
   #       uses: actions/download-artifact@v4
   #       with:
-  #         name: binaries
+  #         name: binaries-signed
   #         path: dist
-  #     - name: Download Windows binaries
+  #     - name: Download signed Windows binaries
   #       uses: actions/download-artifact@v4
   #       with:
-  #         name: binaries-windows
+  #         name: binaries-windows-signed
   #         path: dist
   #     - name: Generate checksum file
   #       run: cd dist && sha256sum * > "k6-${VERSION}-checksums.txt"
@@ -431,7 +551,7 @@ jobs:
 
   # publish-packages:
   #   runs-on: ubuntu-latest
-  #   needs: [configure, build, package-windows]
+  #   needs: [configure, build, sign-windows-installer]
   #   if: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name != 'workflow_dispatch' }}
   #   env:
   #     VERSION: ${{ needs.configure.outputs.k6_version }}
@@ -445,15 +565,15 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         persist-credentials: false
-  #     - name: Download binaries
+  #     - name: Download signed binaries
   #       uses: actions/download-artifact@v4
   #       with:
-  #         name: binaries
+  #         name: binaries-signed
   #         path: dist
-  #     - name: Download Windows binaries
+  #     - name: Download signed Windows binaries
   #       uses: actions/download-artifact@v4
   #       with:
-  #         name: binaries-windows
+  #         name: binaries-windows-signed
   #         path: dist
   #     - name: Rename binaries
   #       # To be consistent with the filenames used in dl.k6.io
@@ -477,15 +597,15 @@ jobs:
   #     - name: Setup docker compose environment
   #       run: |
   #         cat > packaging/.env <<EOF
-  #         AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
-  #         AWS_CF_DISTRIBUTION="${{ env.AWS_CF_DISTRIBUTION }}"
+  #         AWS_ACCESS_KEY_ID=${env.AWS_ACCESS_KEY_ID}
+  #         AWS_CF_DISTRIBUTION="${AWS_CF_DISTRIBUTION}"
   #         AWS_DEFAULT_REGION=us-east-2
-  #         AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
-  #         AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
-  #         PGP_SIGN_KEY_PASSPHRASE=${{ env.PGP_SIGN_KEY_PASSPHRASE }}
-  #         S3_BUCKET=${{ env.S3_BUCKET }}
+  #         AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+  #         AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
+  #         PGP_SIGN_KEY_PASSPHRASE=${PGP_SIGN_KEY_PASSPHRASE}
+  #         S3_BUCKET=${S3_BUCKET}
   #         EOF
-  #         echo "${{ env.PGP_SIGN_KEY }}" > packaging/sign-key.gpg
+  #         echo "${PGP_SIGN_KEY}" > packaging/sign-key.gpg
   #     - name: Publish packages
   #       env:
   #         GITHUB_ACTOR: ${{ github.actor }}
